### ISSUE TITLE
Add functionality to input Ethereum address into the dialog and parse it

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/great-tutorials#1]
Add a feature to paste Ethereum compatible address into the dialogue and parse it.
File where an example dialog is located:
`packages/eth-dev/src/components/levels/GnosisGateway/dialog/dialogParts/Start.jsx`

Example Dialog Screen:
<img width="1393" alt="Screenshot 2023-06-09 at 18 45 22" src="https://github.com/selimerunkut/tutorial-gamification/assets/31136147/ccdf2d06-febe-487b-ac3e-32941f267282">

After the user inputs a contract address and clicks on the button,
(Button Label: Check contract is deployed)
parse that address and check via API if the contract was deployed to gnosisscan
API: https://docs.gnosisscan.io/

Response dialog (success): Contract deployed successfully

Response dialog (fail): Could not find contract

The solution will be used in different tutorials/levels  `packages/eth-dev/src/components/levels/`

in the app so it should be easily replicatable in other folders

like the `GnosisGateway` folder

Alternative solution: 
If adding it to a dialogue and parsing it is to much work:
Alternatively, add the address input field to this kind of window:
`packages/eth-dev/src/components/levels/GnosisGateway/components/ContractWindow.jsx`

**Comment by gitakileus** [comment]
I can't find your telegram.
Can you find me https://t.me/akileus_dev
?
I am interested in this project

**Comment by MubashirWaheed** [comment]
@selimerunkut I am interested in completing this issue. Can you please how you want the dialog box UI to change? 
I believe I know how to check if the contract is deployed on the gnosis chain or not.

**Comment by ashutosh887** [comment]
Please reflect it on GitCoin Website as well that its completed
