### ISSUE TITLE
Add Chatgpt as a dialog partner

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/great-tutorials#2]
User should be able to ask questions about the tutorial he is doing

- [ ] Supply text to chatGPT, so it knows the content of the tutorial

- [ ] Add chatGPT as a dialogue partner to a dialogue window

- [ ]  chatGPT should create 5-10 questions on its own, about the tutorial, that the user can choose from them and get an answer

**Comment by naftalimurgor** [comment]
Hello @selimerunkut 


> 

The tutorial web app already has support for ChatGPT, it's only integrating it into the chat that is left. I have some questions:
- Where are the tutorials from the game that ChatGPT should create the questions from? I can't seem to see the tutorials
