### ISSUE TITLE
BUG: clicking on button, window is not opened and error is displayed

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/great-tutorials#3]
packages/eth-dev/src/components/levels/GnosisGateway/dialog/dialogParts/Start.jsx

After clicking the `Show Contract` Button 

<img width="1436" alt="Screenshot 2023-06-10 at 17 09 43" src="https://github.com/selimerunkut/great-tutorials/assets/31136147/224e5cb1-cce1-468e-a6ab-99805824498a">

error is displayed

<img width="1436" alt="Screenshot 2023-06-10 at 17 07 31" src="https://github.com/selimerunkut/great-tutorials/assets/31136147/5843a949-6382-4e75-b215-2d3e04f1139f">

# Expected Behaviour:

Should open additional window(s) 

Example that is working:

http://localhost:3000/underflow-bug

<img width="1431" alt="Screenshot 2023-06-10 at 17 13 11" src="https://github.com/selimerunkut/great-tutorials/assets/31136147/8b09f4e3-7684-4985-b678-d276651085bf">

**Comment by selimerunkut** [comment]
The same error happens also for the new folder `packages/eth-dev/src/components/levels/Taiko`

```
TypeError: setContractWindowVisibility is not a function
onClick
src/components/levels/Taiko/dialog/dialogParts/Start.jsx:16
```

**Comment by naftalimurgor** [comment]
what path/link throws this error?
